[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Query_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "KEY", DestinationColumnName = "KEY"], [SourceColumnName = "FREQ", DestinationColumnName = "FREQ"], [SourceColumnName = "CURRENCY", DestinationColumnName = "CURRENCY"], [SourceColumnName = "CURRENCY_DENOM", DestinationColumnName = "CURRENCY_DENOM"], [SourceColumnName = "EXR_TYPE", DestinationColumnName = "EXR_TYPE"], [SourceColumnName = "EXR_SUFFIX", DestinationColumnName = "EXR_SUFFIX"], [SourceColumnName = "TIME_PERIOD", DestinationColumnName = "TIME_PERIOD"], [SourceColumnName = "OBS_VALUE", DestinationColumnName = "OBS_VALUE"], [SourceColumnName = "OBS_STATUS", DestinationColumnName = "OBS_STATUS"], [SourceColumnName = "OBS_CONF", DestinationColumnName = "OBS_CONF"], [SourceColumnName = "OBS_PRE_BREAK", DestinationColumnName = "OBS_PRE_BREAK"], [SourceColumnName = "OBS_COM", DestinationColumnName = "OBS_COM"], [SourceColumnName = "TIME_FORMAT", DestinationColumnName = "TIME_FORMAT"], [SourceColumnName = "BREAKS", DestinationColumnName = "BREAKS"], [SourceColumnName = "COLLECTION", DestinationColumnName = "COLLECTION"], [SourceColumnName = "COMPILING_ORG", DestinationColumnName = "COMPILING_ORG"], [SourceColumnName = "DISS_ORG", DestinationColumnName = "DISS_ORG"], [SourceColumnName = "DOM_SER_IDS", DestinationColumnName = "DOM_SER_IDS"], [SourceColumnName = "PUBL_ECB", DestinationColumnName = "PUBL_ECB"], [SourceColumnName = "PUBL_MU", DestinationColumnName = "PUBL_MU"], [SourceColumnName = "PUBL_PUBLIC", DestinationColumnName = "PUBL_PUBLIC"], [SourceColumnName = "UNIT_INDEX_BASE", DestinationColumnName = "UNIT_INDEX_BASE"], [SourceColumnName = "COMPILATION", DestinationColumnName = "COMPILATION"], [SourceColumnName = "COVERAGE", DestinationColumnName = "COVERAGE"], [SourceColumnName = "DECIMALS", DestinationColumnName = "DECIMALS"], [SourceColumnName = "NAT_TITLE", DestinationColumnName = "NAT_TITLE"], [SourceColumnName = "SOURCE_AGENCY", DestinationColumnName = "SOURCE_AGENCY"], [SourceColumnName = "SOURCE_PUB", DestinationColumnName = "SOURCE_PUB"], [SourceColumnName = "TITLE", DestinationColumnName = "TITLE"], [SourceColumnName = "TITLE_COMPL", DestinationColumnName = "TITLE_COMPL"], [SourceColumnName = "UNIT", DestinationColumnName = "UNIT"], [SourceColumnName = "UNIT_MULT", DestinationColumnName = "UNIT_MULT"], [SourceColumnName = "source_url", DestinationColumnName = "source_url"], [SourceColumnName = "loaded_at", DestinationColumnName = "loaded_at"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared Query = let
  Source = Csv.Document(Web.Contents("https://data-api.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?format=csvdata"), [Delimiter = ",", Columns = 32, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"KEY", type text}, {"FREQ", type text}, {"CURRENCY", type text}, {"CURRENCY_DENOM", type text}, {"EXR_TYPE", type text}, {"EXR_SUFFIX", type text}, {"TIME_PERIOD", type date}, {"OBS_VALUE", type number}, {"OBS_STATUS", type text}, {"OBS_CONF", type text}, {"OBS_PRE_BREAK", type text}, {"OBS_COM", type text}, {"TIME_FORMAT", type text}, {"BREAKS", type text}, {"COLLECTION", type text}, {"COMPILING_ORG", type text}, {"DISS_ORG", type text}, {"DOM_SER_IDS", type text}, {"PUBL_ECB", type text}, {"PUBL_MU", type text}, {"PUBL_PUBLIC", type text}, {"UNIT_INDEX_BASE", type text}, {"COMPILATION", type text}, {"COVERAGE", type text}, {"DECIMALS", Int64.Type}, {"NAT_TITLE", type text}, {"SOURCE_AGENCY", type text}, {"SOURCE_PUB", type text}, {"TITLE", type text}, {"TITLE_COMPL", type text}, {"UNIT", type text}, {"UNIT_MULT", Int64.Type}}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Changed column type", "source_url", each "https://data-api.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?format=csvdata"), {{"source_url", type text}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Added custom", "loaded_at", each DateTime.LocalNow()), {{"loaded_at", type datetime}})
in
  #"Added custom 1";
shared Query_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "2e0a9a0f-a9ac-4770-9137-10b52d0b6df6"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "c4c9cf64-1667-4152-bd26-12854382cfbe"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dbo", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "ecb_fx_daily", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
